# Generated by Django 5.2.3 on 2025-07-03 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('instrumento', models.CharField(choices=[('CURSO', 'Instrumento de Avaliação de Cursos de Graduação (ACG)'), ('IES', 'Instrumento de Avaliação Institucional Externo (AIE)')], default='IES', max_length=5, verbose_name='Tipo de Instrumento de Avaliação')),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Instituição')),
                ('sigla', models.CharField(max_length=20)),
                ('codigo_mec', models.IntegerField(unique=True, verbose_name='Código e-MEC')),
                ('imagem_fundo', models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Imagem de Fundo (Opcional)')),
            ],
            options={
                'verbose_name': 'Instituição',
                'verbose_name_plural': 'Instituições',
            },
        ),
        migrations.CreateModel(
            name='Mantenedora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('cnpj', models.CharField(help_text='Formato: XX.XXX.XXX/XXXX-XX', max_length=18, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, verbose_name='Código')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('eixo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='core.eixo')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigo_mec', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Código do Curso (e-MEC)')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instituicao', verbose_name='Instituição')),
            ],
        ),
        migrations.CreateModel(
            name='LogAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=255, verbose_name='Ação Realizada')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
        migrations.AddField(
            model_name='instituicao',
            name='mantenedora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.mantenedora', verbose_name='Mantenedora'),
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Pasta')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('pasta_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subpastas', to='core.pasta', verbose_name='Pasta Pai')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Documento')),
                ('arquivo', models.FileField(upload_to='documentos/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('usuario_upload', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('pasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.pasta')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('foto', models.ImageField(blank=True, default='fotos_perfil/default.png', null=True, upload_to='fotos_perfil/')),
                ('instituicoes', models.ManyToManyField(blank=True, to='core.instituicao', verbose_name='Instituições Acessíveis (Controle Granular)')),
                ('mantenedoras', models.ManyToManyField(blank=True, to='core.mantenedora', verbose_name='Mantenedoras Acessíveis')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessoRegulatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_processo', models.CharField(choices=[('CRIACAO_IES', 'Criação da IES'), ('CREDENCIAMENTO', 'Credenciamento'), ('RECREDENCIAMENTO', 'Recredenciamento'), ('TRANSF_CENTRO', 'Transformação em Centro Universitário/Universidade'), ('AUTORIZACAO_CURSO', 'Autorização de Curso'), ('RECONHECIMENTO_CURSO', 'Reconhecimento de Curso'), ('RENOVACAO_RECONHECIMENTO', 'Renovação de Reconhecimento'), ('EXTINCAO_CURSO', 'Extinção Voluntária de Curso')], max_length=30, verbose_name='Tipo de Processo')),
                ('protocolo_mec', models.CharField(blank=True, max_length=100, verbose_name='Protocolo e-MEC')),
                ('status', models.CharField(choices=[('NAO_INICIADO', 'Não Iniciado'), ('EM_ANDAMENTO', 'Em Andamento'), ('AGUARDANDO_MEC', 'Aguardando MEC'), ('CONCLUIDO', 'Concluído'), ('ARQUIVADO', 'Arquivado')], default='NAO_INICIADO', max_length=20)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.curso', verbose_name='Curso')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instituicao', verbose_name='Instituição')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Processo Regulatório',
                'verbose_name_plural': 'Processos Regulatórios',
            },
        ),
        migrations.CreateModel(
            name='Prazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição do Prazo')),
                ('data', models.DateField(verbose_name='Data')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prazos', to='core.processoregulatorio')),
            ],
            options={
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='PlanoDeAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição da Ação')),
                ('data_limite', models.DateField(blank=True, null=True, verbose_name='Data Limite')),
                ('status', models.CharField(choices=[('NAO_INICIADO', 'Não Iniciado'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído')], default='NAO_INICIADO', max_length=20, verbose_name='Status')),
                ('responsavel_acao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_responsaveis', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela Ação')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_de_acao', to='core.processoregulatorio')),
            ],
        ),
        migrations.AddField(
            model_name='pasta',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastas', to='core.processoregulatorio'),
        ),
        migrations.CreateModel(
            name='Simulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_simulacao', models.CharField(max_length=200, verbose_name='Nome da Simulação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.processoregulatorio')),
            ],
        ),
        migrations.CreateModel(
            name='NotaSimulada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('justificativa', models.TextField(blank=True, help_text='Evidências e justificativas para a nota atribuída')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.indicador')),
                ('simulacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='core.simulacao')),
            ],
        ),
    ]
