# Generated by Django 5.2.3 on 2025-07-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacao',
            name='nome_simulacao',
            field=models.CharField(default=0, help_text='Nome ou título da simulação.', max_length=255),
            preserve_default=False,
        ),
    ]
