# Generated by Django 5.2.3 on 2025-07-05 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_simulacao_nome_simulacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='processoregulatorio',
            name='curso',
            field=models.ForeignKey(blank=True, help_text='Curso relacionado a este processo, se aplicável.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_relacionados', to='core.curso'),
        ),
    ]
