# Generated by Django 5.2.3 on 2025-07-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_processoregulatorio_curso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='codigo_emec',
            new_name='codigo_eMEC',
        ),
        migrations.AddField(
            model_name='planodeacao',
            name='data_limite',
            field=models.DateField(blank=True, help_text='Data limite para a conclusão do Plano de Ação.', null=True),
        ),
    ]
