# Generated by Django 5.2.3 on 2025-07-05 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_codigo_emec_curso_codigo_emec_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prazo',
            name='plano_acao',
        ),
        migrations.AddField(
            model_name='prazo',
            name='processo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='prazos_processo', to='core.processoregulatorio'),
            preserve_default=False,
        ),
    ]
